# Generated by Django 4.2.9 on 2024-02-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DartilOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_order_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره فاکتور شرکت')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کامل')),
                ('order_status', models.CharField(choices=[('بسته بندی نشده', 'بسته بندی نشده'), ('بسته بندی شده', 'بسته بندی شده'), ('ارسال شده', 'ارسال شده')], max_length=50, verbose_name='وضعیت سفارش')),
                ('price', models.CharField(blank=True, max_length=300, null=True, verbose_name='ارزش سفارش')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='dartil_pdfs', verbose_name='فاکتور')),
                ('product_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('product_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سفارش دارتیل ',
                'verbose_name_plural': 'سفارشات دارتیل',
            },
        ),
        migrations.CreateModel(
            name='SnapShopOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره سفارش')),
                ('corp_order_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره فاکتور شرکت')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کامل')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='snappshop_pdfs', verbose_name='فاکتور')),
                ('order_status', models.CharField(choices=[('بسته بندی نشده', 'بسته بندی نشده'), ('بسته بندی شده', 'بسته بندی شده'), ('ارسال شده', 'ارسال شده')], max_length=50, verbose_name='وضعیت سفارش')),
                ('send_status', models.CharField(choices=[('عادی', 'عادی'), ('اکسپرس', 'اکسپرس')], max_length=50, verbose_name='نوع ارسال')),
                ('price', models.CharField(blank=True, max_length=300, null=True, verbose_name='ارزش سفارش')),
                ('product_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('product_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سفارش اسنپ شاپ',
                'verbose_name_plural': 'سفارشات اسنپ شاپ',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
