# Generated by Django 4.2.9 on 2024-02-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dartilorders_snapshoporders_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dartilorders',
            name='order_status',
            field=models.CharField(choices=[('بسته بندی نشده', 'بسته بندی نشده'), ('بسته بندی شده', 'بسته بندی شده'), ('ارسال شده', 'ارسال شده'), ('لغو شده', 'لغو شده')], max_length=50, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='snapshoporders',
            name='order_status',
            field=models.CharField(choices=[('بسته بندی نشده', 'بسته بندی نشده'), ('بسته بندی شده', 'بسته بندی شده'), ('ارسال شده', 'ارسال شده'), ('لغو شده', 'لغو شده')], max_length=50, verbose_name='وضعیت سفارش'),
        ),
    ]
